baseURL: https://cloudseeder.github.io/acme-corp/
languageCode: en-us
title: The Acme Corporation
theme: github.com/hugoinaction/Eclectic
theme: AcmeTheme
enableEmoji: true
enableGitInfo: true
Paginate: 3
