#!/bin/bash

# Add code from template repo buildmeaversion script to ask for a specific version of the template
# hugo mod get github.com/cloudseeder/hugothemeone@v9.0.0

rm -rf ./docs
hugo -D -d docs
git status
echo "Use ^c to exit before the commit"
echo "sleeping 15 seconds"
sleep 15
git add --all
git commit -a -m "new version of the website"
git push acme-corp master
